export type AspectRatio = '16:9' | '1:1' | '4:5' | '9:16'

export type Work = {
  slug: string
  title: string
  category: string
  role: string
  year: number
  ratio: AspectRatio
  poster: string
  posterPosition?: string
  videoKey?: string
  captions?: string
  description?: string
  featured: boolean
  order: number
  visible: boolean
}

export const works: Work[] = [
  {
    slug: 'boots-landscape',
    title: 'Boots — Horizontal',
    category: 'Fashion Concept',
    role: 'Video Editing',
    year: 2026,
    ratio: '16:9',
    poster: '/works/boots-landscape-v01.webp',
    posterPosition: '50% 50%',
    videoKey: 'videos/boots-landscape-v01.mp4',
    featured: true,
    order: 1,
    visible: true,
  },
  {
    slug: 'boots-square',
    title: 'Boots — Square',
    category: 'Fashion Concept',
    role: 'Video Editing',
    year: 2026,
    ratio: '1:1',
    poster: '/works/boots-square-v02.webp',
    posterPosition: '50% 46%',
    videoKey: 'videos/boots-square-v01.mp4',
    featured: true,
    order: 2,
    visible: true,
  },
  {
    slug: 'boots-vertical',
    title: 'Boots — Vertical',
    category: 'Fashion Concept',
    role: 'Video Editing',
    year: 2026,
    ratio: '9:16',
    poster: '/works/boots-vertical-v01.webp',
    posterPosition: '50% 45%',
    videoKey: 'videos/boots-vertical-v01.mp4',
    featured: true,
    order: 3,
    visible: true,
  },
  {
    slug: 'sport-main-film',
    title: 'Sport (Main Film) — Horizontal',
    category: 'Sport Concept',
    role: 'Video Editing',
    year: 2026,
    ratio: '16:9',
    poster: '/works/sport-main-film-v01.webp',
    posterPosition: '50% 50%',
    videoKey: 'videos/sport-main-film-v01.mp4',
    featured: true,
    order: 4,
    visible: true,
  },
  {
    slug: 'sport-hockey',
    title: 'Sport (Hockey) — Square',
    category: 'Sport Concept',
    role: 'Video Editing',
    year: 2026,
    ratio: '1:1',
    poster: '/works/sport-hockey-v01.webp',
    posterPosition: '50% 50%',
    videoKey: 'videos/sport-hockey-v01.mp4',
    featured: true,
    order: 5,
    visible: true,
  },
  {
    slug: 'sport-american-football',
    title: 'Sport (American Football) — Square',
    category: 'Sport Concept',
    role: 'Video Editing',
    year: 2026,
    ratio: '1:1',
    poster: '/works/sport-american-football-v01.webp',
    posterPosition: '50% 50%',
    videoKey: 'videos/sport-american-football-v01.mp4',
    featured: true,
    order: 6,
    visible: true,
  },
  {
    slug: 'sport-soccer',
    title: 'Sport (Soccer) — Square',
    category: 'Sport Concept',
    role: 'Video Editing',
    year: 2026,
    ratio: '1:1',
    poster: '/works/sport-soccer-v01.webp',
    posterPosition: '50% 42%',
    videoKey: 'videos/sport-soccer-v01.mp4',
    featured: true,
    order: 7,
    visible: true,
  },
  {
    slug: 'sport-baseball',
    title: 'Sport (Baseball) — Square',
    category: 'Sport Concept',
    role: 'Video Editing',
    year: 2026,
    ratio: '1:1',
    poster: '/works/sport-baseball-v01.webp',
    posterPosition: '50% 45%',
    videoKey: 'videos/sport-baseball-v01.mp4',
    featured: true,
    order: 8,
    visible: true,
  },
  {
    slug: 'sport-basketball',
    title: 'Sport (Basketball) — Square',
    category: 'Sport Concept',
    role: 'Video Editing',
    year: 2026,
    ratio: '1:1',
    poster: '/works/sport-basketball-v01.webp',
    posterPosition: '50% 42%',
    videoKey: 'videos/sport-basketball-v01.mp4',
    featured: true,
    order: 9,
    visible: true,
  },
  {
    slug: 'pottery-workshop',
    title: 'Pottery Workshop — Horizontal',
    category: 'AI-Generated Film',
    role: 'Creative Direction & Editing',
    year: 2026,
    ratio: '16:9',
    poster: '/works/pottery-workshop-v01.webp',
    posterPosition: '50% 50%',
    videoKey: 'videos/pottery-workshop-v01.mp4',
    description:
      'Graphics, video, music and voice-over were created entirely with AI tools. Creative direction and final editing by the author.',
    featured: true,
    order: 10,
    visible: true,
  },
  {
    slug: 'shoes-square',
    title: 'Shoes — Square',
    category: 'Fashion Concept',
    role: 'Video Editing',
    year: 2026,
    ratio: '1:1',
    poster: '/works/shoes-square-v02.webp',
    posterPosition: '50% 50%',
    videoKey: 'videos/shoes-square-v01.mp4',
    featured: true,
    order: 11,
    visible: true,
  },

  // Hidden placeholders are retained only while the real catalogue is assembled.
  { slug: 'halcyon', title: 'Halcyon', category: 'Brand Film', role: 'Director & Editor', year: 2025, ratio: '16:9', poster: '/works/halcyon.webp', videoKey: 'xionic2-demo-v01.mp4', featured: false, order: 101, visible: false },
  { slug: 'nocturne', title: 'Nocturne', category: 'Music Video', role: 'Editor', year: 2025, ratio: '4:5', poster: '/works/nocturne.webp', videoKey: 'xionic2-demo-v01.mp4', featured: false, order: 102, visible: false },
  { slug: 'field-notes', title: 'Field Notes', category: 'Documentary', role: 'Motion Design', year: 2024, ratio: '16:9', poster: '/works/field-notes.webp', videoKey: 'xionic2-demo-v01.mp4', featured: false, order: 103, visible: false },
  { slug: 'sable', title: 'Sable', category: 'Product Launch', role: 'Motion Design', year: 2024, ratio: '1:1', poster: '/works/sable.webp', videoKey: 'xionic2-demo-v01.mp4', featured: false, order: 104, visible: false },
  { slug: 'vertical-cut', title: 'Vertical Cut', category: 'Social Campaign', role: 'Editor', year: 2024, ratio: '9:16', poster: '/works/vertical-cut.webp', videoKey: 'xionic2-demo-v01.mp4', featured: false, order: 105, visible: false },
  { slug: 'atlas-type', title: 'Atlas Type', category: 'Title Sequence', role: 'Motion Design', year: 2023, ratio: '16:9', poster: '/works/atlas-type.webp', videoKey: 'xionic2-demo-v01.mp4', featured: false, order: 106, visible: false },
  { slug: 'low-tide', title: 'Low Tide', category: 'Short Film', role: 'Colour & Edit', year: 2023, ratio: '4:5', poster: '/works/low-tide.webp', videoKey: 'xionic2-demo-v01.mp4', featured: false, order: 107, visible: false },
  { slug: 'signal', title: 'Signal', category: 'Broadcast ID', role: 'Motion Design', year: 2023, ratio: '16:9', poster: '/works/signal.webp', videoKey: 'xionic2-demo-v01.mp4', featured: false, order: 108, visible: false },
  { slug: 'paper-weight', title: 'Paper Weight', category: 'Editorial Loop', role: 'Animation', year: 2022, ratio: '1:1', poster: '/works/paper-weight.webp', videoKey: 'xionic2-demo-v01.mp4', featured: false, order: 109, visible: false },
  { slug: 'runner', title: 'Runner', category: 'Sports Spot', role: 'Editor', year: 2022, ratio: '9:16', poster: '/works/runner.webp', videoKey: 'xionic2-demo-v01.mp4', featured: false, order: 110, visible: false },
  { slug: 'terrace', title: 'Terrace', category: 'Architecture Reel', role: 'Editor', year: 2022, ratio: '16:9', poster: '/works/terrace.webp', videoKey: 'xionic2-demo-v01.mp4', featured: false, order: 111, visible: false },
  { slug: 'static-bloom', title: 'Static Bloom', category: 'Experimental', role: 'Motion Design', year: 2021, ratio: '4:5', poster: '/works/static-bloom.webp', videoKey: 'xionic2-demo-v01.mp4', featured: false, order: 112, visible: false },
]
